/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tdehlkfovyuwruxdrhyn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkZWhsa2Zvdnl1d3J1eGRyaHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NjE1NzUsImV4cCI6MjA3ODEzNzU3NX0.PvLOnb8mg9D-KTTse-EuN_KYV8jHlhe0F3yYkBFDLR8"